version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: FrontendService/Dockerfile
    container_name: insightops_frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - DataProtection__Keys=/app/Keys
      - Observability__Tempo__Endpoint=http://tempo:4317
      - Observability__Loki__Endpoint=http://loki:3100
      - Observability__Prometheus__Endpoint=http://prometheus:9090
    networks:
      - default
    volumes:
      - ./FrontendService/appsettings.Docker.json:/app/appsettings.Docker.json:ro
      - ./Configurations/DataProtectionKeys:/app/Keys
    ports:
      - "5010:80"
